Generation of checkdata file for check_modpd (coming soon) added.

diff --git a/usr/local/modpd/bin/modpd b/usr/local/modpd/bin/modpd
--- a/usr/local/modpd/bin/modpd
+++ b/usr/local/modpd/bin/modpd
@@ -48,6 +48,7 @@ set -o pipefail || { printf "Setting essential bash option: 'pipefail' was not s
 #-------
 
 trap 'sigHandler SIGUSR1' SIGUSR1 || { printf "Setting essential trap for signal: 'SIGUSR1' was not successful, terminating...\\n" ; exit 247 ; }
+trap 'sigHandler SIGUSR2' SIGUSR2 || { printf "Setting essential trap for signal: 'SIGUSR2' was not successful, terminating...\\n" ; exit 247 ; }
 trap 'sigHandler SIGTERM' SIGTERM || { printf "Setting essential trap for signal: 'SIGTERM' was not successful, terminating...\\n" ; exit 248 ; }
 trap 'sigHandler SIGINT' SIGINT || { printf "Setting essential trap for signal: 'SIGINT' was not successful, terminating...\\n" ; exit 249 ; }
 trap 'sigHandler SIGHUP' SIGHUP || { printf "Setting essential trap for signal: 'SIGHUP' was not successful, terminating...\\n" ; exit 250 ; }
@@ -141,6 +142,104 @@ printStatisticWatchdog()
 	   done
 }
 
+printCheckData()
+{
+	local timestamp=
+
+	if [ "${date_bin_printf:-}" == "1" ] ;then
+		date_cmd="${date_bin:-} '%(${log_timestamp_format})T\\n'"
+	else
+		date_cmd="${date_bin:-} '+${log_timestamp_format}'"
+	fi
+
+	timestamp="$(eval "${date_cmd}")"
+
+	printf "#!/usr/bin/env bash\\n\\n"
+	printf "#-----------------------------------------------------------------------\\n"
+	printf "#\\n"
+	printf "# Automatically generated by:\\t%s\\n" "${script_name}"
+	printf "# Generated at:\\t\\t\\t%s\\n" "${timestamp}"
+	printf "# Author:\\t\\t\\t%s\\n" "${script_author}"
+	printf "# Last modification:\\t\\t%s\\n" "${script_last_modification_date}"
+	printf "# Version:\\t\\t\\t%s\\n" "${script_version}"
+	printf "#\\n"
+	printf "#-----------------------------------------------------------------------\\n\\n\\n\\n"
+	printf "# shows how long %s is running in seconds\\n" "${script_name}"
+	printf "%s_runtime=\"%s\"\\n\\n" "${script_name}" "${SECONDS}"
+	printf "# shows how much nrdp or nsca jobs where handled since program start\\n"
+	printf "script_job_counter_total=\"%s\"\\n\\n" "${script_job_counter_total}"
+	printf "# shows how much nrdp or nsca jobs where handled successfully since program start\\n"
+	printf "script_job_counter_ok=\"%s\"\\n\\n" "${script_job_counter_ok}"
+	printf "# shows how much nrdp or nsca jobs where handled unsuccessfully since program start\\n"
+	printf "script_job_counter_nok=\"%s\"\\n\\n" "${script_job_counter_nok}"
+	printf "# shows how much nrdp or nsca jobs timed out since program start\\n"
+	printf "script_job_counter_timeout=\"%s\"\\n\\n" "${script_job_counter_timeout}"
+	printf "# shows how much host checks where handled since program start\\n"
+	printf "script_host_counter=\"%s\"\\n\\n" "${script_host_counter}"
+	printf "# shows how much service checks where handled since program start\\n"
+	printf "script_service_counter=\"%s\"\\n\\n" "${script_service_counter}"
+	printf "# shows how much invalid datasets where received since program start\\n"
+	printf "script_invalid_data_counter=\"%s\"\\n" "${script_invalid_data_counter}"
+}
+
+printCheckDataWatchdog()
+{
+	local checkdata_interval_helper="$((SECONDS + checkdata_interval))"
+
+	while true
+	   do
+		if [ "${checkdata_interval_helper}" -le "${SECONDS}" ] ;then
+			# shellcheck disable=SC2154
+			${kill_bin} -SIGUSR2 ${script_pid}
+			checkdata_interval_helper="$((SECONDS + checkdata_interval))"
+		fi
+
+		# shellcheck disable=SC2154
+		${sleep_bin} 1
+	   done
+}
+
+checkCheckDataRequirements()
+{
+	if [ "${checkdata_enabled}" == "1" ] ;then
+		local rc=
+
+		logHandler "Checkdata generation is enabled..."
+
+		checkDirectoryPermissions "${checkdata_directory}"
+		rc="$?"
+
+		case "${rc}" in
+			3|7)
+				logHandler "Checkdata directory exists and permissions are ok."
+				;;
+			10)
+				logHandler "Checkdata directory doesnt exist."
+				logHandler "Creating checkdata directory..."
+
+				# shellcheck disable=SC2154
+				${mkdir_bin} -p "${checkdata_directory}" 2>&1 | logHandler
+
+				if [ "${PIPESTATUS[0]}" == "0" ] ;then
+					logHandler "Creating checkdata directory was successful."
+				else
+					logHandler "Creating checkdata directory was not successful, exiting."
+					script_exit_code="10"
+					exit
+				fi
+				;;
+			*)
+				logHandler "Checkdata directory exists, but permissions are not ok, exiting."
+				script_exit_code="11"
+				exit
+				;;
+		esac
+
+		printCheckDataWatchdog &
+		script_checkdata_watchdog_pid="$!"
+	fi
+}
+
 checkOptions()
 {
 	if [ -z "${script_config_file:-}" ] ;then
@@ -148,7 +247,7 @@ checkOptions()
 		printUsage
 
 		script_bypass_exit_routines="1"
-		script_exit_code="10"
+		script_exit_code="20"
 
 		exit
 	fi
@@ -157,7 +256,7 @@ checkOptions()
 		printf "Missing option: -l\\n\\n"
 		printUsage
 
-		script_exit_code="11"
+		script_exit_code="21"
 		script_bypass_exit_routines="1"
 
 		exit
@@ -205,6 +304,11 @@ reloadConfig()
 
 	printStatisticWatchdog &
 	script_statistic_watchdog_pid="$!"
+
+	if [ "${checkdata_enabled}" == "1" ] ;then
+		printCheckDataWatchdog &
+		script_checkdata_watchdog_pid="$!"
+	fi
 
 	if [ "${rc}" == "0" ] ;then
 		logHandlerSetConfig
@@ -502,6 +606,9 @@ sigHandler()
 		SIGUSR1)
 			printStatistic
 			;;
+		SIGUSR2)
+			printCheckData >| "${checkdata_filename}"
+			;;
 		SIGTERM)
 			if [ "${script_shutdown_in_progress}" != "1" ] ;then
 				logHandler "Caught: '${signal}', preparing for exiting..."
@@ -653,13 +760,13 @@ setLock()
 				logHandler "Creating script lock directory was successful."
 			else
 				logHandler "Creating script lock directory was not successful, exiting."
-				script_exit_code="20"
+				script_exit_code="30"
 				exit
 			fi
 			;;
 		*)
 			logHandler "Script lock directory exists, but permissions are not ok, exiting."
-			script_exit_code="21"
+			script_exit_code="31"
 			exit
 			;;
 	esac
@@ -673,7 +780,7 @@ setLock()
 		logHandler "Setting lock was successful."
 	else
 		logHandler "Setting lock was not successful. Maybe another instance has set the lock between checking lock and setting lock."
-		script_exit_code="22"
+		script_exit_code="32"
 		exit
 	fi
 }
@@ -689,7 +796,7 @@ removeLock()
 		logHandler "Removing lock was successful."
 	else
 		logHandler "Removing lock was not successful."
-		script_exit_code="30"
+		script_exit_code="40"
 		exit
 	fi
 }
@@ -867,7 +974,7 @@ checkBashVersion()
 
 	if [ -z "${BASH_VERSINFO[0]}" ] ;then
 		logHandler "Could not determine bash version, exiting."
-		script_exit_code="40"
+		script_exit_code="50"
 		exit
 	else
 		case "${BASH_VERSINFO[0]}" in
@@ -876,7 +983,7 @@ checkBashVersion()
 						;;
 					*)
 						logHandler "Bash version: '${BASH_VERSINFO[0]}' doesnt meet requirements, terminating."
-						script_exit_code="41"
+						script_exit_code="51"
 						exit
 						;;
 		esac
@@ -940,13 +1047,13 @@ checkAlreadyRunningInstance()
 		logHandler "Another instance of: '${script_name}' is currently running (Lockfile: '${script_lock_file}' exists and the following processes: '${running_script_pids[*]}' are running)."
 
 		script_another_instance_is_running="1"
-		script_exit_code="50"
+		script_exit_code="60"
 		exit
 	elif ([ "${rc}" != "0" ] && [ ! -z "${running_script_pids[*]:-}" ]) ;then
 		logHandler "Another instance of: '${script_name}' is currently running (Lockfile: '${script_lock_file}' doesnt exist and the following processes: '${running_script_pids[*]}' are running)."
 
 		script_another_instance_is_running="1"
-		script_exit_code="51"
+		script_exit_code="61"
 		exit
 	fi
 }
@@ -968,7 +1075,7 @@ createNamedPipe()
 			logHandler "Creating named pipe was successful."
 		else
 			logHandler "Creating named pipe was not successful, exiting."
-			script_exit_code="60"
+			script_exit_code="70"
 			exit
 		fi
 	fi
@@ -990,7 +1097,7 @@ removeNamedPipe()
 		exec 3<&-
 	else
 		logHandler "Removing named pipe was not successful, exiting."
-		script_exit_code="70"
+		script_exit_code="80"
 		exit
 	fi
 }
@@ -1015,7 +1122,7 @@ checkNamedPipe()
 			;;
 		*)
 			logHandler "Named pipe exists, but it is not read/writeable, exiting."
-			script_exit_code="80"
+			script_exit_code="90"
 			exit
 			;;
 	esac
@@ -1045,7 +1152,7 @@ buildJobCommand()
 					;;
 				*)
 					logHandler "Invalid obsessing interface defined in config file: '${script_config_file}', exiting."
-					script_exit_code="90"
+					script_exit_code="100"
 					exit
 					;;
 	esac
@@ -1233,22 +1340,22 @@ case "$?" in
 		;;
 	1)
 		printf "Including config file: '%s' was not successful, exiting.\\n" "${script_config_file}"
-		script_exit_code="100"
+		script_exit_code="110"
 		exit
 		;;
 	2)
 		printf "Config file: '%s' does not exist, exiting.\\n" "${script_config_file}"
-		script_exit_code="101"
+		script_exit_code="111"
 		exit
 		;;
 	3)
 		printf "Config file: '%s' exists, but it is not readable, exiting.\\n" "${script_config_file}"
-		script_exit_code="102"
+		script_exit_code="112"
 		exit
 		;;
 	*)
 		printf "Something went terribly wrong in line number: '%s', exiting.\\n" "${LINENO}"
-		script_exit_code="103"
+		script_exit_code="113"
 		exit
 		;;
 esac
@@ -1264,6 +1371,7 @@ checkBashVersion
 checkAlreadyRunningInstance
 printStatisticWatchdog &
 script_statistic_watchdog_pid="$!"
+checkCheckDataRequirements
 createNamedPipe
 setProxy
 buildJobCommand
