Fixed: logStatsWatchdog causes error: "Invalid dataset received" (#86)

diff --git a/etc/init.d/modpd b/etc/init.d/modpd
--- a/etc/init.d/modpd
+++ b/etc/init.d/modpd
@@ -120,6 +120,11 @@ do_start()
 
 	if [ "${DAEMON_RETVAL}" != "0" ]
 	then
+		if [ "${error_mode}" == "1" ]
+		then
+			DAEMON_ARGS="${DAEMON_ARGS} -e"
+		fi
+
 		if [ -n "${DAEMON_USER}" ]
 		then
 			runuser "${DAEMON_USER}" -c "setsid ${DAEMON_PATH} ${DAEMON_ARGS} </dev/null >/dev/null 2>&1 &" </dev/null >/dev/null 2>&1
@@ -254,8 +259,12 @@ case "${1}" in
 	restart)
 		do_restart
 		;;
+	start_error_mode)
+		error_mode="1"
+		do_start
+		;;
 	*)
-		echo "Usage: ${0} {start|stop|status|reload|restart}" >&2
+		echo "Usage: ${0} {start|stop|status|reload|restart|start_error_mode}" >&2
 		exit 3
 		;;
 esac
diff --git a/usr/local/modpd/bin/modpd b/usr/local/modpd/bin/modpd
--- a/usr/local/modpd/bin/modpd
+++ b/usr/local/modpd/bin/modpd
@@ -47,6 +47,19 @@ eprintf()
 
 
 
+#-----------------
+# Check error mode
+#-----------------
+
+if [[ "${@}" =~ ^(.*)-e(.*)$ ]]
+then
+	script_error_mode="1"
+else
+	script_error_mode="0"
+fi
+
+
+
 #------
 # Traps
 #------
@@ -72,11 +85,14 @@ then
 	exit 247
 fi
 
-if ! trap 'signalHandler "ERR" "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}" "${LINENO}" "${BASH_COMMAND}"' ERR
+if [ "${script_error_mode}" == "1" ]
 then
-	eprintf "Setting trap for signal: 'ERR' was not successful."
-	eprintf "Terminating..."
-	exit 247
+	if ! trap 'signalHandler "ERR" "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}" "${LINENO}" "${BASH_COMMAND}"' ERR
+	then
+		eprintf "Setting trap for signal: 'ERR' was not successful."
+		eprintf "Terminating..."
+		exit 247
+	fi
 fi
 
 if ! trap 'signalHandler "EXIT"' EXIT
@@ -145,9 +161,6 @@ signalHandler()
 			;;
 		ERR)
 			logHandler "Caught: '${signal}', in: '${bash_source}', at line number: '${bash_lineno}', command: '${bash_command}'"
-			# deactivated, needs analyzing of some thrown errors
-			#script_exit_code="1"
-			#exit
 			;;
 		EXIT)
 			if [ "${script_config_file_included}" -eq "1" ]
@@ -336,6 +349,8 @@ printUsage()
 	printf "OPTIONS:\\n"
 	printf "   -h\\t\\tShows this help.\\n"
 	printf "   -c\\t\\tPath to config file. (Default: %s)\\n" "${script_config_file}"
+	printf "   -e\\t\\tLog bash errors additionally to: %s\\n" "${script_log_file}"
+	printf "     \\t\\tWARNING: This is not intended for use in a production environment!\\n"
 	printf "   -v\\t\\tShows detailed version information.\\n"
 }
 
@@ -1380,6 +1395,15 @@ dataProcessor()
 				resetCounters
 			fi
 		fi
+
+		if [ "${script_error_mode}" == "1" ]
+		then
+			if timerHandler "${script_error_mode_log_interval}" "${script_timer_last_error_mode_warning_result}"
+			then
+				script_timer_last_error_mode_warning_result="$(( script_timer_last_error_mode_warning_result + 1 ))"
+				logHandler "WARNING: This is not intended for use in a production environment!"
+			fi
+		fi
 	done
 }
 
@@ -1440,6 +1464,7 @@ script_bypass_exit_routines="0"
 script_config_file_included="0"
 script_log_requirements_ok="0"
 script_start_time=
+script_error_mode_log_interval="300"
 script_exit_code="255"
 script_job_pid_1=
 script_job_pid_2=
@@ -1454,6 +1479,7 @@ script_job_data=()
 script_job_raw_data=()
 script_timer_last_debug_log_truncation_result="1"
 script_timer_last_stats_result="1"
+script_timer_last_error_mode_warning_result="1"
 
 
 
@@ -1479,7 +1505,7 @@ then
 	OPTERR="0"
 
 	# shellcheck disable=SC2213
-	while getopts ":c:hv" OPTION
+	while getopts ":c:hve" OPTION
 	do
 		case "${OPTION}" in
 			h)
@@ -1490,6 +1516,9 @@ then
 				;;
 			c)
 				script_config_file="${OPTARG}"
+				;;
+			e)
+				script_error_mode="1"
 				;;
 			v)
 				printScriptInfos
